In [1]:
import pandas as pd
import json
from pathlib import Path

notebook_path = Path().resolve()
gdp_path = notebook_path / "data" / "gdp_per_capita.xlsx"
trade_path = notebook_path / "data" / "trade_by_region.xlsx"

gdp_df = pd.read_excel(gdp_path)
trade_df = pd.read_excel(trade_path)

In [2]:
from data_cleaning import ffill_col, pad_code, split_code_from_name, merge_with_final 

#### GDP per capita

In [3]:
gdp_df

Region     2000     2001     2002     2003     2004  \
0             WHOLE COUNTRY  26348.6  27874.5  28542.9  29102.9  30362.6   
1      MA1 MAINLAND FINLAND  26298.0  27805.9  28477.7  29047.4  30308.2   
2      SA1 Helsinki-Uusimaa  36270.1  38454.8  38552.7  38643.2  40312.2   
3      SA2 Southern Finland  24510.8  25496.1  26535.2  26874.1  28274.5   
4       SA3 Western Finland  22977.4  24934.3  25308.7  26021.4  26790.3   
..                      ...      ...      ...      ...      ...      ...   
114     SK196 Tunturi-Lappi  15833.5  17318.9  17532.8  18249.6  19326.9   
115     SK197 Pohjois-Lappi  16831.4  17697.7  18944.0  19436.5  20576.7   
116   SK211 Mariehamns stad  55008.2  67201.7  63249.5  64894.8  66111.2   
117  SK212 Ålands landsbygd  15005.7  16118.9  19551.3  19139.8  20030.9   
118   SK213 Ålands skärgård  15492.3  17112.8  20994.0  20224.0  21493.8   

        2005     2006     2007     2008  ...     2013     2014     2015  \
0    31388.3  32824.2  35369.4  36559.1  ...  37414.6  37691.9  38359.5   
1    31336.0  32773.7  35328.2  36528.7  ...  37352.3  37626.8  38300.4   
2    41705.0  43989.1  47355.2  48910.2  ...  49746.8  49522.7  51046.2   
3    28920.1  29837.2  31909.0  32610.7  ...  32757.9  33324.9  33634.8   
4    27939.4  28984.6  31658.4  32883.7  ...  33489.3  33730.7  34192.0   
..       ...      ...      ...      ...  ...      ...      ...      ...   
114  20719.5  21910.2  23931.1  27646.8  ...  38063.4  33107.1  38561.2   
115  22876.0  23965.0  24254.0  26963.6  ...  34416.5  37545.2  39502.1   
116  67262.4  64953.7  65050.8  61924.5  ...  73320.6  77689.8  76942.9   
117  20355.4  22774.3  24374.4  24964.3  ...  30088.5  28278.3  28423.4   
118  21938.9  27234.7  24613.9  26041.4  ...  25469.2  25215.9  24965.2   

        2016     2017     2018     2019     2020     2021     2022  
0    39254.8  40794.7  42045.9  43197.2  42749.8  44895.0  47897.6  
1    39206.3  40751.2  42025.2  43169.1  42752.0  44882.5  47874.7  
2    51914.0  53512.8  54982.0  56756.6  55424.5  57622.9  60375.8  
3    34555.8  36405.5  37394.7  38162.7  37852.5  39788.7  42355.0  
4    34652.5  35861.8  37086.4  37870.4  37835.0  40081.9  42685.8  
..       ...      ...      ...      ...      ...      ...      ...  
114  42374.2  43613.5  42995.3  46392.0  51480.3  50834.7  58063.0  
115  39789.2  48466.2  51082.0  45736.6  49815.2  59296.8  69084.8  
116  74140.8  75018.3  69275.6  71537.6  56690.4  65761.7  79980.2  
117  28626.2  28606.3  26375.7  28128.2  28584.5  31092.4  30625.0  
118  24991.7  27348.3  27389.6  27997.3  28538.4  26926.6  18509.1  

[119 rows x 24 columns]

Dataset gdp_df contains:
- Provinces
- Regions
- Well-being areas
- Sub-regions

We will only be using regions. (Perhaps it may make sense to use sub-regions in the future, if we see that municipalities are too small.)

In [4]:
gdp_df = gdp_df[gdp_df["Region"].astype(str).str.contains("MK")]
gdp_df

Region     2000     2001     2002     2003     2004  \
6                MK01 Uusimaa  36270.1  38454.8  38552.7  38643.2  40312.2   
7      MK02 Southwest Finland  26094.0  26551.8  29570.2  29065.6  30627.2   
8              MK04 Satakunta  23325.3  25814.2  26215.8  26399.7  26385.4   
9             MK05 Kanta-Häme  20656.4  22253.3  22360.0  23708.2  25107.3   
10             MK06 Pirkanmaa  24923.3  27338.9  28117.4  28831.7  30063.5   
11           MK07 Päijät-Häme  20701.5  22123.4  21861.5  23141.2  24072.2   
12           MK08 Kymenlaakso  27357.0  28665.5  28068.5  27953.3  30399.0   
13         MK09 South Karelia  25954.6  26856.8  26612.6  27694.5  27903.7   
14            MK10 South Savo  17678.1  18777.3  19360.0  20455.1  21581.9   
15            MK11 North Savo  19493.5  20881.4  21324.0  22128.3  22665.7   
16         MK12 North Karelia  18953.8  19629.0  19770.6  21001.9  22359.0   
17       MK13 Central Finland  22274.9  24194.7  24662.2  24956.7  24994.0   
18    MK14 South Ostrobothnia  17770.9  18789.6  19287.6  20298.9  21197.0   
19          MK15 Ostrobothnia  24586.3  25674.6  24545.7  26223.3  27724.4   
20  MK16 Central Ostrobothnia  19287.7  20553.5  19949.6  21453.9  22675.0   
21    MK17 North Ostrobothnia  23714.4  23434.3  26498.6  27968.8  29206.9   
22                MK18 Kainuu  17383.6  19189.8  19774.7  20063.6  21012.3   
23               MK19 Lapland  22140.9  22450.5  23023.6  23545.4  24999.6   
26                 MK21 Åland  31352.2  37019.8  37439.4  37726.9  38756.2   

       2005     2006     2007     2008  ...     2013     2014     2015  \
6   41705.0  43989.1  47355.2  48910.2  ...  49746.8  49522.7  51046.2   
7   31344.2  32924.9  36024.5  36529.7  ...  33902.3  34387.2  34417.8   
8   27884.1  29245.8  31059.4  32021.8  ...  34143.3  35164.0  36178.0   
9   25497.5  26220.6  27819.6  30068.9  ...  31740.2  31335.8  31491.3   
10  31234.4  31899.4  34830.6  36086.9  ...  34972.6  34596.1  34608.1   
11  25006.1  25399.4  26594.8  28140.5  ...  29858.5  30513.9  30755.5   
12  31270.8  31359.5  31679.1  30890.4  ...  32115.4  32837.7  34903.2   
13  27889.7  28703.2  31543.9  31602.5  ...  35479.0  37266.2  36577.3   
14  22528.8  23271.5  25984.0  25908.8  ...  28566.0  29834.7  29441.1   
15  24076.4  24992.9  27091.2  28875.0  ...  30119.2  30842.8  31361.6   
16  23104.1  24552.4  25472.6  25804.0  ...  28679.5  29585.1  29068.8   
17  25611.6  26733.1  29206.1  30453.9  ...  29780.5  30466.5  31730.4   
18  22170.7  23398.3  26219.4  27038.3  ...  29691.6  30191.5  30080.7   
19  29309.3  30575.7  33754.3  35600.9  ...  38498.2  38482.3  38897.3   
20  23873.0  27712.6  29713.8  32043.2  ...  32638.1  34545.2  35158.2   
21  29820.8  29694.0  32443.9  33475.4  ...  31787.8  31461.1  30722.1   
22  21057.0  22930.0  24048.5  25513.2  ...  25493.1  26532.4  26235.2   
23  25095.5  28565.8  28257.1  29282.1  ...  32764.5  33009.1  34671.4   
26  39409.8  40132.4  40737.3  39881.7  ...  46934.8  47674.9  47390.7   

       2016     2017     2018     2019     2020     2021     2022  
6   51914.0  53512.8  54982.0  56756.6  55424.5  57622.9  60375.8  
7   36103.0  38440.6  39544.4  40404.6  39752.0  41181.0  44629.6  
8   34955.6  36167.8  36858.4  36564.9  37034.6  39248.0  42468.6  
9   32119.7  33124.4  33256.0  34667.5  35522.7  37967.0  38841.6  
10  35947.5  37247.0  38781.9  39863.9  40148.2  41910.2  44133.8  
11  31679.5  32139.8  32759.5  32905.6  32745.5  34467.9  37708.0  
12  34794.8  37371.4  39846.3  41287.3  41506.5  42936.9  44126.7  
13  36455.6  38887.9  39219.9  38900.7  37378.9  41539.3  43646.0  
14  30397.6  31079.4  32249.7  32910.2  33034.8  34167.4  37847.9  
15  32053.9  33681.4  35220.2  36065.6  35762.4  37853.5  42213.7  
16  30174.8  30573.3  32994.7  33428.7  32441.6  35017.0  37992.8  
17  32743.0  33816.4  35405.7  35809.8  35079.4  37388.2  40650.4  
18  30080.8  31720.9  32190.7  33884.6  34185.9  36042.7  38416.9  
19  38584.7  39225.9  40432.1

Now, we restructure the dataset from the following...

Region | 2000 | 2001 | ... | 2021 | 2022
---|---|---|---|---|---
01 | 36270.1 | 38454.8 | ... | 57622.9 | 60375.8
... | ... | ... | ...| ... | ...
21 | 31352.2 | 37019.8 | ... | 44250.6 | 48912.8

so that it is fits the following format:

Region | Year | GDP per capita (euro at current prices)
---|---|---
01 | 2000 | 36270.1
01 | 2001 | 38454.8
... | ... | ... | ...
21 | 2022 | 48912.8

In [5]:
long_gdp_df = gdp_df.melt(
    id_vars=["Region"],          # keep Region as is
    var_name="Year",             # new column name for former column headers
    value_name="GDP per capita (euro at current prices)"  # name for values
)
long_gdp_df

Region  Year  GDP per capita (euro at current prices)
0                 MK01 Uusimaa  2000                                  36270.1
1       MK02 Southwest Finland  2000                                  26094.0
2               MK04 Satakunta  2000                                  23325.3
3              MK05 Kanta-Häme  2000                                  20656.4
4               MK06 Pirkanmaa  2000                                  24923.3
..                         ...   ...                                      ...
432  MK16 Central Ostrobothnia  2022                                  40369.2
433    MK17 North Ostrobothnia  2022                                  41666.7
434                MK18 Kainuu  2022                                  42125.5
435               MK19 Lapland  2022                                  46618.7
436                 MK21 Åland  2022                                  48912.8

[437 rows x 3 columns]

In [6]:
long_gdp_df = split_code_from_name(long_gdp_df, "Region", code_length=2)
long_gdp_df

Region  Year  GDP per capita (euro at current prices)
0       01  2000                                  36270.1
1       02  2000                                  26094.0
2       04  2000                                  23325.3
3       05  2000                                  20656.4
4       06  2000                                  24923.3
..     ...   ...                                      ...
432     16  2022                                  40369.2
433     17  2022                                  41666.7
434     18  2022                                  42125.5
435     19  2022                                  46618.7
436     21  2022                                  48912.8

[437 rows x 3 columns]

### Trade

In [7]:
trade_df

Year  Region                                 Flow  \
0    202412       1       Imports by countries of origin   
1    202412       1  Exports by countries of destination   
2    202412       2       Imports by countries of origin   
3    202412       2  Exports by countries of destination   
4    202412       4       Imports by countries of origin   
..      ...     ...                                  ...   
375  201512      18  Exports by countries of destination   
376  201512      19       Imports by countries of origin   
377  201512      19  Exports by countries of destination   
378  201512      21       Imports by countries of origin   
379  201512      21  Exports by countries of destination   

     Cum. statistical value (euro) from the beginning of the year  
0                                          42750000000             
1                                          22418000000             
2                                           4737000000             
3                                           6718000000             
4                                           3332000000             
..                                                 ...             
375                                          145000000             
376                                         1695000000             
377                                         3875000000             
378                                          559000000             
379                                          103000000             

[380 rows x 4 columns]

We restructure the dataset from...

Year | Region | Flow | Cum. statistical value (euro) from the beginning of the year
---|---|---|---
2024 | 1 Uusimaa | Imports by countries of origin | 42750000000.0
2024 | 1 Uusimaa | Exports by countries of origin | 22418000000.0
... | ... | ... | ...

To the following structure:

Region | Year | Imports (euro) | Exports (euro)
---|---|---|---
1 Uusimaa | 2024 | 42750000000.0 | 22418000000.0
... | ... | ... | ...


In [8]:
# Pivot wider
wide_trade_df = trade_df.pivot_table(
    index=["Region", "Year"],  # keep Region and Year
    columns="Flow",            # values in Flow become columns
    values="Cum. statistical value (euro) from the beginning of the year",
    aggfunc="sum"              # in case of duplicates
).reset_index()

wide_trade_df = pad_code(wide_trade_df, "Region", code_length=2)
wide_trade_df

Flow Region    Year  Exports by countries of destination  \
0        01  201512                          16912000000   
1        01  201612                          15850000000   
2        01  201712                          18255000000   
3        01  201812                          18717000000   
4        01  201912                          19361000000   
..      ...     ...                                  ...   
185      21  202012                             85000000   
186      21  202112                            113000000   
187      21  202212                            163000000   
188      21  202312                            184000000   
189      21  202412                            122000000   

Flow  Imports by countries of origin  
0                        33474000000  
1                        34441000000  
2                        36814000000  
3                        38838000000  
4                        38416000000  
..                               ...  
185                        309000000  
186                        385000000  
187                       1098000000  
188                        375000000  
189                        284000000  

[190 rows x 4 columns]

In [9]:
wide_trade_df = wide_trade_df.rename(columns={
    "Imports by countries of origin": "Imports (euro)",
    "Exports by countries of destination": "Exports (euro)"
})

wide_trade_df["Year"] = wide_trade_df["Year"].astype(str).str[:4]
wide_trade_df

Flow Region  Year  Exports (euro)  Imports (euro)
0        01  2015     16912000000     33474000000
1        01  2016     15850000000     34441000000
2        01  2017     18255000000     36814000000
3        01  2018     18717000000     38838000000
4        01  2019     19361000000     38416000000
..      ...   ...             ...             ...
185      21  2020        85000000       309000000
186      21  2021       113000000       385000000
187      21  2022       163000000      1098000000
188      21  2023       184000000       375000000
189      21  2024       122000000       284000000

[190 rows x 4 columns]

### Merge GDP per capita and Trade

In [10]:
final_df = pd.merge(
    left=wide_trade_df,
    right=long_gdp_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  Exports (euro)  Imports (euro)  \
0       01  2000             NaN             NaN   
1       01  2001             NaN             NaN   
2       01  2002             NaN             NaN   
3       01  2003             NaN             NaN   
4       01  2004             NaN             NaN   
..     ...   ...             ...             ...   
470     21  2020      85000000.0    3.090000e+08   
471     21  2021     113000000.0    3.850000e+08   
472     21  2022     163000000.0    1.098000e+09   
473     21  2023     184000000.0    3.750000e+08   
474     21  2024     122000000.0    2.840000e+08   

     GDP per capita (euro at current prices)  
0                                    36270.1  
1                                    38454.8  
2                                    38552.7  
3                                    38643.2  
4                                    40312.2  
..                                       ...  
470                                  39532.8  
471                                  44250.6  
472                                  48912.8  
473                                      NaN  
474                                      NaN  

[475 rows x 5 columns]

In [11]:
# reorder columns
final_df = final_df[
    ["Region", "Year", "GDP per capita (euro at current prices)",
     "Imports (euro)", "Exports (euro)"]
]

final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
470     21  2020                                  39532.8    3.090000e+08   
471     21  2021                                  44250.6    3.850000e+08   
472     21  2022                                  48912.8    1.098000e+09   
473     21  2023                                      NaN    3.750000e+08   
474     21  2024                                      NaN    2.840000e+08   

     Exports (euro)  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
..              ...  
470      85000000.0  
471     113000000.0  
472     163000000.0  
473     184000000.0  
474     122000000.0  

[475 rows x 5 columns]

### Gross value added


In [16]:
import pandas as pd
from pathlib import Path

notebook_path = Path().resolve()
gross_value_path = notebook_path / "data" / "gross_value_added.csv"

gross_value_df = pd.read_csv(gross_value_path, dtype={"Region": str, "Year": str})
gross_value_df

Region  Year  \
0       01  2000   
1       01  2001   
2       01  2002   
3       01  2003   
4       01  2004   
..     ...   ...   
451     21  2019   
452     21  2020   
453     21  2021   
454     21  2022   
455     21  2023   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
451                                               30.2                                   
452                                               31.3                                   
453                                               29.3                                   
454                                               21.7                                   
455                                               26.4                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
451                                                1.6                      
452                                                1.5                      
453                                                1.7                      
454                                                1.7                      
455                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
451                                              111.7               
452                                              109.5               
453                                              132.4               
454                                              135.7               
455                                                NaN               

     Gross value added (millions of euro), D, E Electricity, gas, steam and air conditioning and water supply; sewerage and waste management (35-39)  \
0                                                964.9                                                                                                 
1                                               1049.8                                                                                                 
2                                               1145.8                                                                                                 
3                                               1354.2                                                                                                 
4                                               1343.7                                                                                                 
..  

In [17]:
final_df = pd.merge(
    left=final_df,
    right=gross_value_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
470     21  2020                                  39532.8    3.090000e+08   
471     21  2021                                  44250.6    3.850000e+08   
472     21  2022                                  48912.8    1.098000e+09   
473     21  2023                                      NaN    3.750000e+08   
474     21  2024                                      NaN    2.840000e+08   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
470      85000000.0   
471     113000000.0   
472     163000000.0   
473     184000000.0   
474     122000000.0   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
470                                               31.3                                   
471                                               29.3                                   
472                                               21.7                                   
473                                               26.4                                   
474                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
470                                                1.5                      
471                                                1.7                      
472                                                1.7                      
473                                                NaN                      
474                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
470                                              109.5               
471                                              132.4               
472                                              135.7               
473                                                NaN               
474                       

### Hours worked

In [18]:
hours_worked_path = notebook_path / "data" / "hours_worked.xlsx"
hours_worked_df = pd.read_excel(hours_worked_path)
hours_worked_df

Region  Year  Hours worked, domestic (1 000 000 h)
0    MK01 Uusimaa  2000                              1251.708
1             NaN  2001                              1267.148
2             NaN  2002                              1283.743
3             NaN  2003                              1261.744
4             NaN  2004                              1261.911
..            ...   ...                                   ...
432           NaN  2018                                28.497
433           NaN  2019                                28.935
434           NaN  2020                                28.121
435           NaN  2021                                26.624
436           NaN  2022                                27.677

[437 rows x 3 columns]

In [19]:
# ffill Region
hours_worked_df["Region"] = hours_worked_df["Region"].ffill()
hours_worked_df

Region  Year  Hours worked, domestic (1 000 000 h)
0    MK01 Uusimaa  2000                              1251.708
1    MK01 Uusimaa  2001                              1267.148
2    MK01 Uusimaa  2002                              1283.743
3    MK01 Uusimaa  2003                              1261.744
4    MK01 Uusimaa  2004                              1261.911
..            ...   ...                                   ...
432    MK21 Åland  2018                                28.497
433    MK21 Åland  2019                                28.935
434    MK21 Åland  2020                                28.121
435    MK21 Åland  2021                                26.624
436    MK21 Åland  2022                                27.677

[437 rows x 3 columns]

In [20]:
hours_worked_df["Region"] = (
    hours_worked_df["Region"]
    .astype(str)
    .str.split(" ").str[0]  # take only region code
    .str[-2:]
)
hours_worked_df

Region  Year  Hours worked, domestic (1 000 000 h)
0       01  2000                              1251.708
1       01  2001                              1267.148
2       01  2002                              1283.743
3       01  2003                              1261.744
4       01  2004                              1261.911
..     ...   ...                                   ...
432     21  2018                                28.497
433     21  2019                                28.935
434     21  2020                                28.121
435     21  2021                                26.624
436     21  2022                                27.677

[437 rows x 3 columns]

In [21]:
hours_worked_df["Year"] = hours_worked_df["Year"].astype(str)

In [22]:
final_df = pd.merge(
    left=final_df,
    right=hours_worked_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
470     21  2020                                  39532.8    3.090000e+08   
471     21  2021                                  44250.6    3.850000e+08   
472     21  2022                                  48912.8    1.098000e+09   
473     21  2023                                      NaN    3.750000e+08   
474     21  2024                                      NaN    2.840000e+08   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
470      85000000.0   
471     113000000.0   
472     163000000.0   
473     184000000.0   
474     122000000.0   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
470                                               31.3                                   
471                                               29.3                                   
472                                               21.7                                   
473                                               26.4                                   
474                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
470                                                1.5                      
471                                                1.7                      
472                                                1.7                      
473                                                NaN                      
474                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
470                                              109.5               
471                                              132.4               
472                                              135.7               
473                                                NaN               
474                       

In [23]:
final_df = final_df.sort_values(["Region", "Year"])
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
470     21  2020                                  39532.8    3.090000e+08   
471     21  2021                                  44250.6    3.850000e+08   
472     21  2022                                  48912.8    1.098000e+09   
473     21  2023                                      NaN    3.750000e+08   
474     21  2024                                      NaN    2.840000e+08   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
470      85000000.0   
471     113000000.0   
472     163000000.0   
473     184000000.0   
474     122000000.0   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
470                                               31.3                                   
471                                               29.3                                   
472                                               21.7                                   
473                                               26.4                                   
474                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
470                                                1.5                      
471                                                1.7                      
472                                                1.7                      
473                                                NaN                      
474                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
470                                              109.5               
471                                              132.4               
472                                              135.7               
473                                                NaN               
474                       

### Workplace and population (Kareem's dataset)

In [40]:
workplace_population_path = notebook_path / "data" / "workplaceANDpopulation.csv"
workplace_population_df = pd.read_csv(workplace_population_path, dtype={"Region": str, "Year": str})
workplace_population_df

Region  Year  A Agriculture, forestry and fishing (TP)  \
0       01  2010                                      3192   
1       01  2011                                      3062   
2       01  2012                                      3186   
3       01  2013                                      3153   
4       01  2014                                      3028   
..     ...   ...                                       ...   
261     21  2019                                       239   
262     21  2020                                       218   
263     21  2021                                       229   
264     21  2022                                       242   
265     21  2023                                       224   

     B Mining and quarrying (TP)  C Manufacturing (TP)  \
0                            327                 65439   
1                            247                 64598   
2                            174                 63248   
3                            232                 59868   
4                            255                 57208   
..                           ...                   ...   
261                           10                   490   
262                           12                   507   
263                           11                   615   
264                           12                   623   
265                           12                   606   

     Children aged 0 to 14 (PT)  \
0                        227717   
1                        229572   
2                        231952   
3                        235090   
4                        238213   
..                          ...   
261                        4074   
262                        4094   
263                        4095   
264                        4059   
265                        4021   

     D Electricity, gas, steam and air conditioning supply (TP)  \
0                                                 4276            
1                                                 4427            
2                                                 4362            
3                                                 4503            
4                                                 4417            
..                                                 ...            
261                                                109            
262                                                105            
263                                                107            
264                                                111            
265                                                118            

     E Water supply; sewerage, waste management and remediation activities (TP)  \
0                                                 2336                            
1                                                 2433                            
2                                                 2290                            
3                                                 2207                            
4                                                 2302                            
..                                                 ...                            
261                                                 54                            
262                                                 53                            
263                                                 54                            
264                                                 47                            
265                                                 48                            

     Employed (PT)  F Construction (TP)  ...  \
0           666292                39210  ...   
1           675755                41838  ...   
2           677658                42438  ...   
3           671826                43012  ...   
4           667124                42715  ...   
..             ...                  ...  ...   
261

In [41]:
final_df = pd.merge(
    left=final_df,
    right=workplace_population_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
470     21  2020                                  39532.8    3.090000e+08   
471     21  2021                                  44250.6    3.850000e+08   
472     21  2022                                  48912.8    1.098000e+09   
473     21  2023                                      NaN    3.750000e+08   
474     21  2024                                      NaN    2.840000e+08   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
470      85000000.0   
471     113000000.0   
472     163000000.0   
473     184000000.0   
474     122000000.0   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
470                                               31.3                                   
471                                               29.3                                   
472                                               21.7                                   
473                                               26.4                                   
474                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
470                                                1.5                      
471                                                1.7                      
472                                                1.7                      
473                                                NaN                      
474                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
470                                              109.5               
471                                              132.4               
472                                              135.7               
473                                                NaN               
474                       

### Vacancies and unemployment (Ignacio)

In [45]:
vacancies_unemployment_path = notebook_path / "data" / "vacancies_unemployment.csv"
vacancies_unemployment_df = pd.read_csv(vacancies_unemployment_path, dtype={"Region": str, "Year": str})
vacancies_unemployment_df

Region  Year  Unemployed jobseekers  Vacancies
0       01  2008                  41777      11294
1       01  2009                  57263       7083
2       01  2010                  60495       7830
3       01  2011                  55729      10660
4       01  2012                  57845      10939
..     ...   ...                    ...        ...
337     21  2021                   1027        287
338     21  2022                    661        380
339     21  2023                    618        361
340     21  2024                    676        338
341     21  2025                    777        296

[342 rows x 4 columns]

In [46]:
final_df = pd.merge(
    left=final_df,
    right=vacancies_unemployment_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
489     21  2021                                  44250.6    3.850000e+08   
490     21  2022                                  48912.8    1.098000e+09   
491     21  2023                                      NaN    3.750000e+08   
492     21  2024                                      NaN    2.840000e+08   
493     21  2025                                      NaN             NaN   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
489     113000000.0   
490     163000000.0   
491     184000000.0   
492     122000000.0   
493             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
489                                               29.3                                   
490                                               21.7                                   
491                                               26.4                                   
492                                                NaN                                   
493                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
489                                                1.7                      
490                                                1.7                      
491                                                NaN                      
492                                                NaN                      
493                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
489                                              132.4               
490                                              135.7               
491                                                NaN               
492                                                NaN               
493                       

### Enterprises, bankruptcies (Ignacio)

In [51]:
# data from years 2005 - 2013
enterprise_path = notebook_path / "data" / "enterprises_bankrupcies_investments.csv"
enterprise_stock_of_industry_df = pd.read_csv(enterprise_path, dtype={"Municipality": str, "Year": str})
# get only rows where Municiaplity is TOTAL
enterprise_stock_of_industry_df = enterprise_stock_of_industry_df[enterprise_stock_of_industry_df["Municipality"] == "TOTAL"]
# drop municipality column
enterprise_stock_of_industry_df = enterprise_stock_of_industry_df.drop(columns=["Municipality"])
enterprise_stock_of_industry_df

Region  Year  \
6872       1  2000   
6873       1  2001   
6874       1  2002   
6875       1  2003   
6876       1  2004   
...      ...   ...   
7339      21  2020   
7340      21  2021   
7341      21  2022   
7342      21  2023   
7343      21  2024   

      A Agriculture, forestry and fishing Net opening of enterprises (unit)  \
6872                                                NaN                       
6873                                                NaN                       
6874                                                NaN                       
6875                                                0.0                       
6876                                                0.0                       
...                                                 ...                       
7339                                                3.0                       
7340                                               16.0                       
7341                                                6.0                       
7342                                                8.0                       
7343                                                5.0                       

      B Mining and quarrying Net opening of enterprises (unit)  \
6872                                                NaN          
6873                                                NaN          
6874                                                NaN          
6875                                                0.0          
6876                                                0.0          
...                                                 ...          
7339                                                0.0          
7340                                               -1.0          
7341                                                0.0          
7342                                                0.0          
7343                                                0.0          

      C Manufacturing Net opening of enterprises (unit)  \
6872                                                NaN   
6873                                                NaN   
6874                                                NaN   
6875                                                0.0   
6876                                                0.0   
...                                                 ...   
7339                                                8.0   
7340                                                4.0   
7341                                                2.0   
7342                                                4.0   
7343                                               11.0   

      D Electricity,  gas, steam and air conditioning supply Net opening of enterprises (unit)  \
6872                                                NaN                                          
6873                                                NaN                                          
6874                                                NaN                                          
6875                                                0.0                                          
6876                                                0.0                                          
...                                                 ...                                          
7339                                                1.0                                          
7340                                                2.0                                          
7341                                                7.0                                          
7342                                                9.0                                          
7343                                                1.0                                          

      E Water supply; sewerage, waste management and remediation activities Net opening of enterprises (unit)  \


In [52]:
# pad enterprise_stock_of_industry_df Region codes to 2 characters
enterprise_stock_of_industry_df["Region"] = (
    enterprise_stock_of_industry_df["Region"]
    .astype(str)
    .str.zfill(2)
)
enterprise_stock_of_industry_df

Region  Year  \
6872     01  2000   
6873     01  2001   
6874     01  2002   
6875     01  2003   
6876     01  2004   
...     ...   ...   
7339     21  2020   
7340     21  2021   
7341     21  2022   
7342     21  2023   
7343     21  2024   

      A Agriculture, forestry and fishing Net opening of enterprises (unit)  \
6872                                                NaN                       
6873                                                NaN                       
6874                                                NaN                       
6875                                                0.0                       
6876                                                0.0                       
...                                                 ...                       
7339                                                3.0                       
7340                                               16.0                       
7341                                                6.0                       
7342                                                8.0                       
7343                                                5.0                       

      B Mining and quarrying Net opening of enterprises (unit)  \
6872                                                NaN          
6873                                                NaN          
6874                                                NaN          
6875                                                0.0          
6876                                                0.0          
...                                                 ...          
7339                                                0.0          
7340                                               -1.0          
7341                                                0.0          
7342                                                0.0          
7343                                                0.0          

      C Manufacturing Net opening of enterprises (unit)  \
6872                                                NaN   
6873                                                NaN   
6874                                                NaN   
6875                                                0.0   
6876                                                0.0   
...                                                 ...   
7339                                                8.0   
7340                                                4.0   
7341                                                2.0   
7342                                                4.0   
7343                                               11.0   

      D Electricity,  gas, steam and air conditioning supply Net opening of enterprises (unit)  \
6872                                                NaN                                          
6873                                                NaN                                          
6874                                                NaN                                          
6875                                                0.0                                          
6876                                                0.0                                          
...                                                 ...                                          
7339                                                1.0                                          
7340                                                2.0                                          
7341                                                7.0                                          
7342                                                9.0                                          
7343                                                1.0                                          

      E Water supply; sewerage, waste management and remediation activities Net opening of enterprises (unit)  \
6872       

In [53]:
final_df = pd.merge(
    left=final_df,
    right=enterprise_stock_of_industry_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
489     21  2021                                  44250.6    3.850000e+08   
490     21  2022                                  48912.8    1.098000e+09   
491     21  2023                                      NaN    3.750000e+08   
492     21  2024                                      NaN    2.840000e+08   
493     21  2025                                      NaN             NaN   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
489     113000000.0   
490     163000000.0   
491     184000000.0   
492     122000000.0   
493             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
489                                               29.3                                   
490                                               21.7                                   
491                                               26.4                                   
492                                                NaN                                   
493                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
489                                                1.7                      
490                                                1.7                      
491                                                NaN                      
492                                                NaN                      
493                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
489                                              132.4               
490                                              135.7               
491                                                NaN               
492                                                NaN               
493                       

### Household income, expenditure, and debt (Khanh)

In [63]:
income_expenditure_debt_path = notebook_path / "data" / "Household income, expenditure and debt.csv"
income_expenditure_debt_df = pd.read_csv(income_expenditure_debt_path, dtype={"Region": str, "Municipality": str, "Year": str})
income_expenditure_debt_df

region municipality  year  Median of debt for All debts  \
0          1          018  2003                       59388.0   
1          1          018  2004                       58848.0   
2          1          018  2005                       69631.0   
3          1          018  2006                       81678.0   
4          1          018  2007                       84166.0   
...      ...          ...   ...                           ...   
7208      21        Total  2018                           NaN   
7209      21        Total  2019                           NaN   
7210      21        Total  2020                           NaN   
7211      21        Total  2021                           NaN   
7212      21        Total  2022                           NaN   

      Median of debt for Consumption debts and other debts  \
0                                               11716.0      
1                                               12650.0      
2                                               14614.0      
3                                               16863.0      
4                                               16356.0      
...                                                 ...      
7208                                                NaN      
7209                                                NaN      
7210                                                NaN      
7211                                                NaN      
7212                                                NaN      

      Median of debt for Debts charged on business activities and a source of income  \
0                                               40324.0                                
1                                               39612.0                                
2                                               43714.0                                
3                                               39098.0                                
4                                               41275.0                                
...                                                 ...                                
7208                                                NaN                                
7209                                                NaN                                
7210                                                NaN                                
7211                                                NaN                                
7212                                                NaN                                

      Median of debt for Housing loan debts  \
0                                   61190.0   
1                                   65961.0   
2                                   79899.0   
3                                   88128.0   
4                                   97776.0   
...                                     ...   
7208                                    NaN   
7209                                    NaN   
7210                                    NaN   
7211                                    NaN   
7212                                    NaN   

      Median of debt for Study loan debts  Mean of debt for All debts  \
0                                  4344.0                  80012.0000   
1                                  4353.0                  83471.0000   
2                                  4612.0                 105231.0000   
3                                  4851.0                 110952.0000   
4                                  3894.0                 118083.0000   
...                                   ...                         ...   
7208                              53626.0                 135757.5000   
7209                              55975.0                 136165.5000   
7210                              65660.0                 139930.0625   
7211                              64339.0                 136181.1875   
7212                              66582.0              

In [64]:
income_expenditure_debt_df = income_expenditure_debt_df[income_expenditure_debt_df["municipality"] == "Total"]
# replace "Total" with "TOTAL" to be consistent
income_expenditure_debt_df["municipality"] = "TOTAL"
income_expenditure_debt_df


/var/folders/0_/jmr7585j3xl32_rz685ds6rc0000gn/T/ipykernel_32185/2076211584.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  income_expenditure_debt_df["municipality"] = "TOTAL"


region municipality  year  Median of debt for All debts  \
572        1        TOTAL  2000                           NaN   
573        1        TOTAL  2001                           NaN   
574        1        TOTAL  2002                           NaN   
575        1        TOTAL  2003                           NaN   
576        1        TOTAL  2004                           NaN   
...      ...          ...   ...                           ...   
7208      21        TOTAL  2018                           NaN   
7209      21        TOTAL  2019                           NaN   
7210      21        TOTAL  2020                           NaN   
7211      21        TOTAL  2021                           NaN   
7212      21        TOTAL  2022                           NaN   

      Median of debt for Consumption debts and other debts  \
572                                                 NaN      
573                                                 NaN      
574                                                 NaN      
575                                                 NaN      
576                                                 NaN      
...                                                 ...      
7208                                                NaN      
7209                                                NaN      
7210                                                NaN      
7211                                                NaN      
7212                                                NaN      

      Median of debt for Debts charged on business activities and a source of income  \
572                                                 NaN                                
573                                                 NaN                                
574                                                 NaN                                
575                                                 NaN                                
576                                                 NaN                                
...                                                 ...                                
7208                                                NaN                                
7209                                                NaN                                
7210                                                NaN                                
7211                                                NaN                                
7212                                                NaN                                

      Median of debt for Housing loan debts  \
572                                     NaN   
573                                     NaN   
574                                     NaN   
575                                     NaN   
576                                     NaN   
...                                     ...   
7208                                    NaN   
7209                                    NaN   
7210                                    NaN   
7211                                    NaN   
7212                                    NaN   

      Median of debt for Study loan debts  Mean of debt for All debts  \
572                                   NaN                         NaN   
573                                   NaN                         NaN   
574                                   NaN                         NaN   
575                                5930.0                72939.884615   
576                                5885.0                81832.230769   
...                                   ...                         ...   
7208                              53626.0               135757.500000   
7209                              55975.0               136165.500000   
7210                              65660.0               139930.062500   
7211                              64339.0               136181.187500   
7212                              66582.0              

In [65]:
income_expenditure_debt_df.columns

Index(['region', 'municipality', 'year', 'Median of debt for All debts',
       'Median of debt for Consumption debts and other debts',
       'Median of debt for Debts charged on business activities and a source of income',
       'Median of debt for Housing loan debts',
       'Median of debt for Study loan debts', 'Mean of debt for All debts',
       'Mean of debt for Consumption debts and other debts',
       'Mean of debt for Debts charged on business activities and a source of income',
       'Mean of debt for Housing loan debts',
       'Mean of debt for Study loan debts', 'B2N Operating surplus, net',
       'B3N Mixed income, net', 'D11R Wages and salaries received, income',
       'D12R Employer's social security contributions, income',
       'D4OMR  Property income, (incl. holding gains and losses), income',
       'D4K Property income, expenditure', 'B5N Net national income',
       'D62R Social benefits other than social transfers in kind, income',
       'D7R Other curre

In [66]:
# rename columns
income_expenditure_debt_df = income_expenditure_debt_df.rename(columns={
    'region': "Region", 
    'municipality': "Municipality", 
    'year': "Year", 
    'Median of debt for All debts': 'Median of debt for all debts',
    'Median of debt for Consumption debts and other debts': "Median of debt for consumption debts and other debts",
    'Median of debt for Debts charged on business activities and a source of income': "Median of debt for debts charged on business activities and a source of income",
    'Median of debt for Housing loan debts': 'Median of debt for housing loan debts',
    'Median of debt for Study loan debts': 'Median of debt for study loan debts', 
    'Mean of debt for All debts': 'Mean of debt for all debts',
    'Mean of debt for Consumption debts and other debts': "Mean of debt for consumption debts and other debts",
    'Mean of debt for Debts charged on business activities and a source of income': "Mean of debt for debts charged on business activities and a source of income",
    'Mean of debt for Housing loan debts': "Mean of debt for housing loan debts",
    'Mean of debt for Study loan debts': "Mean of debt for study loan debts", 
    'B2N Operating surplus, net': "Operating surplus, net",
    'B3N Mixed income, net': "Mixed income, net", 
    'D11R Wages and salaries received, income': "Wages and salaries received, income",
    "D12R Employer's social security contributions, income": "Employer's social security contributions, income",
    'D4OMR  Property income, (incl. holding gains and losses), income': "Property income, (incl. holding gains and losses), income",
    'D4K Property income, expenditure': "Property income, expenditure", 
    'B5N Net national income': "Net national income",
    'D62R Social benefits other than social transfers in kind, income': "Social benefits other than social transfers in kind, income",
    'D7R Other current transfers, income': "Other current transfers, income",
    'D5K Income, property and other direct taxes excl. capital taxes, expenditure': "Income, property and other direct taxes excl. capital taxes, expenditure",
    "D61K Employer's social security contributions": "Employer's social security contributions",
    'D7K Other current transfers, expenditure': "Other current transfers, expenditure",
    'B6N Disposable income, net': "Disposable income, net"
})

income_expenditure_debt_df

Region Municipality  Year  Median of debt for all debts  \
572        1        TOTAL  2000                           NaN   
573        1        TOTAL  2001                           NaN   
574        1        TOTAL  2002                           NaN   
575        1        TOTAL  2003                           NaN   
576        1        TOTAL  2004                           NaN   
...      ...          ...   ...                           ...   
7208      21        TOTAL  2018                           NaN   
7209      21        TOTAL  2019                           NaN   
7210      21        TOTAL  2020                           NaN   
7211      21        TOTAL  2021                           NaN   
7212      21        TOTAL  2022                           NaN   

      Median of debt for consumption debts and other debts  \
572                                                 NaN      
573                                                 NaN      
574                                                 NaN      
575                                                 NaN      
576                                                 NaN      
...                                                 ...      
7208                                                NaN      
7209                                                NaN      
7210                                                NaN      
7211                                                NaN      
7212                                                NaN      

      Median of debt for debts charged on business activities and a source of income  \
572                                                 NaN                                
573                                                 NaN                                
574                                                 NaN                                
575                                                 NaN                                
576                                                 NaN                                
...                                                 ...                                
7208                                                NaN                                
7209                                                NaN                                
7210                                                NaN                                
7211                                                NaN                                
7212                                                NaN                                

      Median of debt for housing loan debts  \
572                                     NaN   
573                                     NaN   
574                                     NaN   
575                                     NaN   
576                                     NaN   
...                                     ...   
7208                                    NaN   
7209                                    NaN   
7210                                    NaN   
7211                                    NaN   
7212                                    NaN   

      Median of debt for study loan debts  Mean of debt for all debts  \
572                                   NaN                         NaN   
573                                   NaN                         NaN   
574                                   NaN                         NaN   
575                                5930.0                72939.884615   
576                                5885.0                81832.230769   
...                                   ...                         ...   
7208                              53626.0               135757.500000   
7209                              55975.0               136165.500000   
7210                              65660.0               139930.062500   
7211                              64339.0               136181.187500   
7212                              66582.0              

In [67]:
# pad Region column with zeros to length 2
income_expenditure_debt_df["Region"] = income_expenditure_debt_df["Region"].astype(str).str.zfill(2)
# drop municipality column
income_expenditure_debt_df = income_expenditure_debt_df.drop(columns=["Municipality"])
income_expenditure_debt_df

Region  Year  Median of debt for all debts  \
572      01  2000                           NaN   
573      01  2001                           NaN   
574      01  2002                           NaN   
575      01  2003                           NaN   
576      01  2004                           NaN   
...     ...   ...                           ...   
7208     21  2018                           NaN   
7209     21  2019                           NaN   
7210     21  2020                           NaN   
7211     21  2021                           NaN   
7212     21  2022                           NaN   

      Median of debt for consumption debts and other debts  \
572                                                 NaN      
573                                                 NaN      
574                                                 NaN      
575                                                 NaN      
576                                                 NaN      
...                                                 ...      
7208                                                NaN      
7209                                                NaN      
7210                                                NaN      
7211                                                NaN      
7212                                                NaN      

      Median of debt for debts charged on business activities and a source of income  \
572                                                 NaN                                
573                                                 NaN                                
574                                                 NaN                                
575                                                 NaN                                
576                                                 NaN                                
...                                                 ...                                
7208                                                NaN                                
7209                                                NaN                                
7210                                                NaN                                
7211                                                NaN                                
7212                                                NaN                                

      Median of debt for housing loan debts  \
572                                     NaN   
573                                     NaN   
574                                     NaN   
575                                     NaN   
576                                     NaN   
...                                     ...   
7208                                    NaN   
7209                                    NaN   
7210                                    NaN   
7211                                    NaN   
7212                                    NaN   

      Median of debt for study loan debts  Mean of debt for all debts  \
572                                   NaN                         NaN   
573                                   NaN                         NaN   
574                                   NaN                         NaN   
575                                5930.0                72939.884615   
576                                5885.0                81832.230769   
...                                   ...                         ...   
7208                              53626.0               135757.500000   
7209                              55975.0               136165.500000   
7210                              65660.0               139930.062500   
7211                              64339.0               136181.187500   
7212                              66582.0               130566.437500   

      Mean of debt for consumption debts and other debts  \
572                                                 NaN    
573                         

In [69]:
income_expenditure_debt_df["Year"] = income_expenditure_debt_df["Year"].astype(str)

final_df = pd.merge(
    left=final_df,
    right=income_expenditure_debt_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  Imports (euro)  \
0       01  2000                                  36270.1             NaN   
1       01  2001                                  38454.8             NaN   
2       01  2002                                  38552.7             NaN   
3       01  2003                                  38643.2             NaN   
4       01  2004                                  40312.2             NaN   
..     ...   ...                                      ...             ...   
489     21  2021                                  44250.6    3.850000e+08   
490     21  2022                                  48912.8    1.098000e+09   
491     21  2023                                      NaN    3.750000e+08   
492     21  2024                                      NaN    2.840000e+08   
493     21  2025                                      NaN             NaN   

     Exports (euro)  \
0               NaN   
1               NaN   
2               NaN   
3               NaN   
4               NaN   
..              ...   
489     113000000.0   
490     163000000.0   
491     184000000.0   
492     122000000.0   
493             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
489                                               29.3                                   
490                                               21.7                                   
491                                               26.4                                   
492                                                NaN                                   
493                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
489                                                1.7                      
490                                                1.7                      
491                                                NaN                      
492                                                NaN                      
493                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
489                                              132.4               
490                                              135.7               
491                                                NaN               
492                                                NaN               
493                       

### Education, population (Alina)

In [72]:
education_population_path = notebook_path / "data" / "education_population.csv"
education_population_df = pd.read_csv(education_population_path, dtype={"Region": str, "Municipality": str, "Year": str})
education_population_df

Region Municipality  Year  \
0                01          018  2010   
1                01          018  2011   
2                01          018  2012   
3                01          018  2013   
4                01          018  2014   
...             ...          ...   ...   
4601  WHOLE COUNTRY        TOTAL  2019   
4602  WHOLE COUNTRY        TOTAL  2020   
4603  WHOLE COUNTRY        TOTAL  2021   
4604  WHOLE COUNTRY        TOTAL  2022   
4605  WHOLE COUNTRY        TOTAL  2023   

      Academic degree, higher university level degree (population)  \
0                                                   147              
1                                                   161              
2                                                   165              
3                                                   172              
4                                                   182              
...                                                 ...              
4601                                             514587              
4602                                             532586              
4603                                             548937              
4604                                             564198              
4605                                             589149              

      Academic degree, lowest level tertiary and lower university level degrees (population)  \
0                                                   603                                        
1                                                   619                                        
2                                                   644                                        
3                                                   656                                        
4                                                   667                                        
...                                                 ...                                        
4601                                             984147                                        
4602                                             992956                                        
4603                                            1002269                                        
4604                                            1008725                                        
4605                                            1024213                                        

      Aged 18 or over, total (population)  Basic level studies (population)  \
0                                    3628                              1222   
1                                    3677                              1210   
2                                    3721                              1174   
3                                    3713                              1121   
4                                    3788                              1117   
...                                   ...                               ...   
4601                              4476235                           1040869   
4602                              4492267                           1023598   
4603                              4512724                           1010850   
4604                              4537778                           1007600   
4605                              4581646                            999988   

      Matriculation examination (population)  Vocational diploma (population)  \
0                                        188                             1468   
1                                        168                             1519   
2                                        175                             1563   
3                                        183                             1581   
4                                        193                             1629   
...                                      ...                              ...  

In [73]:
# only get rows where Municipality is TOTAL
education_population_df = education_population_df[education_population_df["Municipality"] == "TOTAL"]
# drop Municipality column
education_population_df = education_population_df.drop(columns=["Municipality"])
education_population_df

Region  Year  \
364              01  2010   
365              01  2011   
366              01  2012   
367              01  2013   
368              01  2014   
...             ...   ...   
4601  WHOLE COUNTRY  2019   
4602  WHOLE COUNTRY  2020   
4603  WHOLE COUNTRY  2021   
4604  WHOLE COUNTRY  2022   
4605  WHOLE COUNTRY  2023   

      Academic degree, higher university level degree (population)  \
364                                              170085              
365                                              175624              
366                                              181894              
367                                              189729              
368                                              195740              
...                                                 ...              
4601                                             514587              
4602                                             532586              
4603                                             548937              
4604                                             564198              
4605                                             589149              

      Academic degree, lowest level tertiary and lower university level degrees (population)  \
364                                              268622                                        
365                                              273653                                        
366                                              278338                                        
367                                              284718                                        
368                                              288609                                        
...                                                 ...                                        
4601                                             984147                                        
4602                                             992956                                        
4603                                            1002269                                        
4604                                            1008725                                        
4605                                            1024213                                        

      Aged 18 or over, total (population)  Basic level studies (population)  \
364                               1192450                            326127   
365                               1207731                            323954   
366                               1224564                            322619   
367                               1240610                            318573   
368                               1254763                            316050   
...                                   ...                               ...   
4601                              4476235                           1040869   
4602                              4492267                           1023598   
4603                              4512724                           1010850   
4604                              4537778                           1007600   
4605                              4581646                            999988   

      Matriculation examination (population)  Vocational diploma (population)  \
364                                   131079                           296512   
365                                   131535                           302945   
366                                   131229                           310440   
367                                   128730                           318824   
368                                   128229                           326106   
...                                      ...                              ...   
4601                                  305649                          1630983   
4602                                  305721                          163

In [75]:
final_df = pd.merge(
    left=final_df,
    right=education_population_df,
    how="outer",
    on=["Region", "Year"]
)
final_df

Region  Year  GDP per capita (euro at current prices)  \
0               01  2000                                  36270.1   
1               01  2001                                  38454.8   
2               01  2002                                  38552.7   
3               01  2003                                  38643.2   
4               01  2004                                  40312.2   
..             ...   ...                                      ...   
503  WHOLE COUNTRY  2019                                      NaN   
504  WHOLE COUNTRY  2020                                      NaN   
505  WHOLE COUNTRY  2021                                      NaN   
506  WHOLE COUNTRY  2022                                      NaN   
507  WHOLE COUNTRY  2023                                      NaN   

     Imports (euro)  Exports (euro)  \
0               NaN             NaN   
1               NaN             NaN   
2               NaN             NaN   
3               NaN             NaN   
4               NaN             NaN   
..              ...             ...   
503             NaN             NaN   
504             NaN             NaN   
505             NaN             NaN   
506             NaN             NaN   
507             NaN             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
503                                                NaN                                   
504                                                NaN                                   
505                                                NaN                                   
506                                                NaN                                   
507                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
503                                                NaN                      
504                                                NaN                      
505                                                NaN                      
506                                                NaN                      
507                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
503                                                NaN               
504                                                NaN               
505                                                NaN               
506     

### Final formatting

In [76]:
final_df = final_df.sort_values(["Region", "Year"])
final_df

Region  Year  GDP per capita (euro at current prices)  \
0               01  2000                                  36270.1   
1               01  2001                                  38454.8   
2               01  2002                                  38552.7   
3               01  2003                                  38643.2   
4               01  2004                                  40312.2   
..             ...   ...                                      ...   
503  WHOLE COUNTRY  2019                                      NaN   
504  WHOLE COUNTRY  2020                                      NaN   
505  WHOLE COUNTRY  2021                                      NaN   
506  WHOLE COUNTRY  2022                                      NaN   
507  WHOLE COUNTRY  2023                                      NaN   

     Imports (euro)  Exports (euro)  \
0               NaN             NaN   
1               NaN             NaN   
2               NaN             NaN   
3               NaN             NaN   
4               NaN             NaN   
..              ...             ...   
503             NaN             NaN   
504             NaN             NaN   
505             NaN             NaN   
506             NaN             NaN   
507             NaN             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
503                                                NaN                                   
504                                                NaN                                   
505                                                NaN                                   
506                                                NaN                                   
507                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
503                                                NaN                      
504                                                NaN                      
505                                                NaN                      
506                                                NaN                      
507                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
503                                                NaN               
504                                                NaN               
505                                                NaN               
506     

In [77]:
final_df

Region  Year  GDP per capita (euro at current prices)  \
0               01  2000                                  36270.1   
1               01  2001                                  38454.8   
2               01  2002                                  38552.7   
3               01  2003                                  38643.2   
4               01  2004                                  40312.2   
..             ...   ...                                      ...   
503  WHOLE COUNTRY  2019                                      NaN   
504  WHOLE COUNTRY  2020                                      NaN   
505  WHOLE COUNTRY  2021                                      NaN   
506  WHOLE COUNTRY  2022                                      NaN   
507  WHOLE COUNTRY  2023                                      NaN   

     Imports (euro)  Exports (euro)  \
0               NaN             NaN   
1               NaN             NaN   
2               NaN             NaN   
3               NaN             NaN   
4               NaN             NaN   
..              ...             ...   
503             NaN             NaN   
504             NaN             NaN   
505             NaN             NaN   
506             NaN             NaN   
507             NaN             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
0                                                255.5                                   
1                                                235.4                                   
2                                                246.1                                   
3                                                235.6                                   
4                                                233.9                                   
..                                                 ...                                   
503                                                NaN                                   
504                                                NaN                                   
505                                                NaN                                   
506                                                NaN                                   
507                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
0                                                 40.8                      
1                                                 43.4                      
2                                                 39.1                      
3                                                 34.6                      
4                                                 42.8                      
..                                                 ...                      
503                                                NaN                      
504                                                NaN                      
505                                                NaN                      
506                                                NaN                      
507                                                NaN                      

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
503                                                NaN               
504                                                NaN               
505                                                NaN               
506     

In [78]:
# save to csv
output_path = notebook_path / "data" / "final_economic_data.csv"
final_df.to_csv(output_path, index=False)

In [ ]:
import numpy as np

def fill_region_totals(df, total_value="TOTAL"):
    # Identify numeric columns to sum
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    # Exclude group columns and municipality column from numeric columns
    numeric_cols = [col for col in numeric_cols if col not in ["Region", "Year", "Municipality"]]

    # For each region and year, fill missing TOTALs
    for (region, year), group in df.groupby(["Region", "Year"]):
        # Get the index of the TOTAL row (if it exists)
        mask_total = (
            (df["Region"] == region) &
            (df["Year"] == year) &
            (df["Municipality"] == total_value)
        )
        if mask_total.any():
            idx_total = df[mask_total].index[0]
            # Only fill if all values are missing (NaN/None) for each column
            for col in numeric_cols:
                if pd.isna(df.at[idx_total, col]):
                    # Sum all municipality values for this region/year/column
                    vals = group[group["Municipality"] != total_value][col]
                    summed = vals.sum(skipna=True)
                    # Only fill if there is at least one non-missing value
                    if not vals.isna().all():
                        df.at[idx_total, col] = summed
    return df

final_df = fill_region_totals(final_df)
final_df

Region Municipality  Year  GDP per capita (euro at current prices)  \
3        01          018  2003                                      NaN   
30       01          018  2004                                      NaN   
57       01          018  2005                                      NaN   
84       01          018  2006                                      NaN   
111      01          018  2007                                      NaN   
...     ...          ...   ...                                      ...   
7508     21        TOTAL  2020                                  39532.8   
7525     21        TOTAL  2021                                  44250.6   
7542     21        TOTAL  2022                                  48912.8   
7559     21        TOTAL  2023                                      NaN   
7576     21        TOTAL  2024                                      NaN   

      Imports (euro)  Exports (euro)  \
3                NaN             NaN   
30               NaN             NaN   
57               NaN             NaN   
84               NaN             NaN   
111              NaN             NaN   
...              ...             ...   
7508    5.976800e+10    5.744000e+10   
7525    7.293600e+10    6.890800e+10   
7542    9.246900e+10    8.188500e+10   
7559    7.684900e+10    7.636200e+10   
7576    7.455700e+10    7.210400e+10   

      Gross value added (millions of euro), A Agriculture, forestry and fishing (01-03)  \
3                                                   NaN                                   
30                                                  NaN                                   
57                                                  NaN                                   
84                                                  NaN                                   
111                                                 NaN                                   
...                                                 ...                                   
7508                                               31.3                                   
7525                                               29.3                                   
7542                                               21.7                                   
7559                                               26.4                                   
7576                                                NaN                                   

     Gross value added (millions of euro), B Mining and quarrying (05-09)  \
3                                                   NaN                     
30                                                  NaN                     
57                                                  NaN                     
84                                                  NaN                     
111                                                 NaN                     
...                                                 ...                     
7508                                                1.5                     
7525                                                1.7                     
7542                                                1.7                     
7559                                               <NA>                     
7576                                                NaN                     

     Gross value added (millions of euro), F Construction (41-43)  \
3                                                   NaN             
30                                                  NaN             
57                                                  NaN             
84                                                  NaN             
111                                                 NaN             
...                                                 ...             
7508                                               89.4             
7525                                               94

In [73]:
# save final df to csv
output_path = notebook_path / "data" / "final_economic_data.csv"
final_df.to_csv(output_path, index=False)

### Actually final formatting (merging Ignacio's dataset that has been supplemented w Finnish data)

In [43]:
final_df_path = notebook_path / "data" / "final_economic_data.csv"
enterprise_path = notebook_path / "data" / "enterprises_bankrupcies_investments.csv"

final_df = pd.read_csv(final_df_path, dtype={"Region": str, "Municipality": str, "Year": str})
enterprise_df = pd.read_csv(enterprise_path, dtype={"Region": str, "Municipality": str, "Year": str})

final_df


Region Municipality  Year  GDP per capita (euro)  Imports (euro)  \
0        01          018  2003                    NaN             NaN   
1        01          018  2004                    NaN             NaN   
2        01          018  2005                    NaN             NaN   
3        01          018  2006                    NaN             NaN   
4        01          018  2007                    NaN             NaN   
...     ...          ...   ...                    ...             ...   
7588     21        TOTAL  2020                39532.8    5.976800e+10   
7589     21        TOTAL  2021                44250.6    7.293600e+10   
7590     21        TOTAL  2022                48912.8    9.246900e+10   
7591     21        TOTAL  2023                    NaN    7.684900e+10   
7592     21        TOTAL  2024                    NaN    7.455700e+10   

      Exports (euro)  \
0                NaN   
1                NaN   
2                NaN   
3                NaN   
4                NaN   
...              ...   
7588    5.744000e+10   
7589    6.890800e+10   
7590    8.188500e+10   
7591    7.636200e+10   
7592    7.210400e+10   

      Gross value added (millions of euro), A Agriculture, forestry and fishing  \
0                                                   NaN                           
1                                                   NaN                           
2                                                   NaN                           
3                                                   NaN                           
4                                                   NaN                           
...                                                 ...                           
7588                                               31.3                           
7589                                               29.3                           
7590                                               21.7                           
7591                                               26.4                           
7592                                                NaN                           

      Gross value added (millions of euro), B Mining and quarrying  \
0                                                   NaN              
1                                                   NaN              
2                                                   NaN              
3                                                   NaN              
4                                                   NaN              
...                                                 ...              
7588                                                1.5              
7589                                                1.7              
7590                                                1.7              
7591                                                NaN              
7592                                                NaN              

      Gross value added (millions of euro), F Construction  \
0                                                   NaN      
1                                                   NaN      
2                                                   NaN      
3                                                   NaN      
4                                                   NaN      
...                                                 ...      
7588                                               89.4      
7589                                               94.3      
7590                                               83.0      
7591                                                NaN      
7592                                                NaN      

      Gross value added (millions of euro), G Wholesale and retail trade; repair of motor vehicles and motorcycles  \
0                                                   NaN                                                              
1                   

In [4]:
enterprise_df

Region Municipality  Year  \
0         01          018  2003   
1         01          018  2004   
2         01          018  2005   
3         01          018  2006   
4         01          018  2007   
...      ...          ...   ...   
12955     21        TOTAL  2020   
12956     21        TOTAL  2021   
12957     21        TOTAL  2022   
12958     21        TOTAL  2023   
12959     21        TOTAL  2024   

       A Agriculture, forestry and fishing Net opening of enterprises (unit)  \
0                                                    NaN                       
1                                                    NaN                       
2                                                    NaN                       
3                                                    NaN                       
4                                                    NaN                       
...                                                  ...                       
12955                                                3.0                       
12956                                               16.0                       
12957                                                6.0                       
12958                                                8.0                       
12959                                                5.0                       

       B Mining and quarrying Net opening of enterprises (unit)  \
0                                                    NaN          
1                                                    NaN          
2                                                    NaN          
3                                                    NaN          
4                                                    NaN          
...                                                  ...          
12955                                                0.0          
12956                                               -1.0          
12957                                                0.0          
12958                                                0.0          
12959                                                0.0          

       C Manufacturing Net opening of enterprises (unit)  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
12955                                                8.0   
12956                                                4.0   
12957                                                2.0   
12958                                                4.0   
12959                                               11.0   

       D Electricity,  gas, steam and air conditioning supply Net opening of enterprises (unit)  \
0                                                    NaN                                          
1                                                    NaN                                          
2                                                    NaN                                          
3                                                    NaN                                          
4                                                    NaN                                          
...                                                  ...                                          
12955                                                1.0                                          
12956                                                2.0                                          
12957                                                7.0                                          
12958                                                9.0                                          
12959    

In [7]:
# remove identical rows
enterprise_df = enterprise_df.drop_duplicates()
enterprise_df

Region Municipality  Year  \
0         01          018  2003   
1         01          018  2004   
2         01          018  2005   
3         01          018  2006   
4         01          018  2007   
...      ...          ...   ...   
12955     21        TOTAL  2020   
12956     21        TOTAL  2021   
12957     21        TOTAL  2022   
12958     21        TOTAL  2023   
12959     21        TOTAL  2024   

       A Agriculture, forestry and fishing Net opening of enterprises (unit)  \
0                                                    NaN                       
1                                                    NaN                       
2                                                    NaN                       
3                                                    NaN                       
4                                                    NaN                       
...                                                  ...                       
12955                                                3.0                       
12956                                               16.0                       
12957                                                6.0                       
12958                                                8.0                       
12959                                                5.0                       

       B Mining and quarrying Net opening of enterprises (unit)  \
0                                                    NaN          
1                                                    NaN          
2                                                    NaN          
3                                                    NaN          
4                                                    NaN          
...                                                  ...          
12955                                                0.0          
12956                                               -1.0          
12957                                                0.0          
12958                                                0.0          
12959                                                0.0          

       C Manufacturing Net opening of enterprises (unit)  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
12955                                                8.0   
12956                                                4.0   
12957                                                2.0   
12958                                                4.0   
12959                                               11.0   

       D Electricity,  gas, steam and air conditioning supply Net opening of enterprises (unit)  \
0                                                    NaN                                          
1                                                    NaN                                          
2                                                    NaN                                          
3                                                    NaN                                          
4                                                    NaN                                          
...                                                  ...                                          
12955                                                1.0                                          
12956                                                2.0                                          
12957                                                7.0                                          
12958                                                9.0                                          
12959    

Can't merge this with the final dataset. There are repeat years for municipalities (e.g. 01, 018 has each year following 2013 four times). Dropping duplicate rows drops 750 rows, but does not entirely resolve the issue above due to differing values across the same year that is being repeated. For example, year 2013 for municipality 018, region 01, has values 28.00 and 29.00 for column "C Manufacturing Stock of Enterprises (unit)"

In [5]:
final_df = merge_with_final(enterprise_df, final_df)
final_df

Region Municipality  Year  GDP per capita (euro)  Imports (euro)  \
0         01        TOTAL  2000                36270.1             NaN   
1         01        TOTAL  2001                38454.8             NaN   
2         01        TOTAL  2002                38552.7             NaN   
3         01          018  2003                    NaN             NaN   
4         01          049  2003                    NaN             NaN   
...      ...          ...   ...                    ...             ...   
13300     21          478  2025                    NaN             NaN   
13301     21          736  2025                    NaN             NaN   
13302     21          766  2025                    NaN             NaN   
13303     21          771  2025                    NaN             NaN   
13304     21          941  2025                    NaN             NaN   

       Exports (euro)  \
0                 NaN   
1                 NaN   
2                 NaN   
3                 NaN   
4                 NaN   
...               ...   
13300             NaN   
13301             NaN   
13302             NaN   
13303             NaN   
13304             NaN   

       Gross value added (millions of euro), A Agriculture, forestry and fishing  \
0                                                  255.5                           
1                                                  235.4                           
2                                                  246.1                           
3                                                    NaN                           
4                                                    NaN                           
...                                                  ...                           
13300                                                NaN                           
13301                                                NaN                           
13302                                                NaN                           
13303                                                NaN                           
13304                                                NaN                           

       Gross value added (millions of euro), B Mining and quarrying  \
0                                                   40.8              
1                                                   43.4              
2                                                   39.1              
3                                                    NaN              
4                                                    NaN              
...                                                  ...              
13300                                                NaN              
13301                                                NaN              
13302                                                NaN              
13303                                                NaN              
13304                                                NaN              

       Gross value added (millions of euro), F Construction  \
0                                                 2501.6      
1                                                 2766.6      
2                                                 2449.9      
3                                                    NaN      
4                                                    NaN      
...                                                  ...      
13300                                                NaN      
13301                                                NaN      
13302                                                NaN      
13303                                                NaN      
13304                                                NaN      

       Gross value added (millions of euro), G Wholesale and retail trade; repair of motor vehicles and motorcycles  \
0                                                 5985.4                      

In [ ]:
# feature selection??

### Add missing industries to final dataset

In [32]:
import pandas as pd
from pathlib import Path

notebook_path = Path().resolve()
final_path = notebook_path / "data" / "final_economic_data.csv"
regional_path = notebook_path / "data" / "regional_economic_data.csv"
remaining_industries_path = notebook_path / "data" / "remaining_industries.xlsx"

final_df = pd.read_csv(final_path, dtype={"Region": str, "Municipality": str, "Year": int})
regional_df = pd.read_csv(regional_path, dtype={"Region": str, "Municipality": str, "Year": int})
# get only columns Region, Year, and those with "Gross value added" in their name
remaining_industries_df = pd.read_excel(remaining_industries_path, dtype={"Region": str, "Year": int})
remaining_industries_df = remaining_industries_df[["Region", "Year"] + [col for col in remaining_industries_df.columns if "Gross value added" in col]]

remaining_industries_df

Region  Year  \
0    MK01 Uusimaa  2000   
1             NaN  2001   
2             NaN  2002   
3             NaN  2003   
4             NaN  2004   
..            ...   ...   
424           NaN  2018   
425           NaN  2019   
426           NaN  2020   
427           NaN  2021   
428           NaN  2022   

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
424                                               94.4               
425                                              111.7               
426                                              109.5               
427                                              132.4               
428                                              135.7               

     Gross value added (millions of euro), D, E Electricity, gas, steam and air conditioning and water supply; sewerage and waste management (35-39)  \
0                                                964.9                                                                                                 
1                                               1049.8                                                                                                 
2                                               1145.8                                                                                                 
3                                               1354.2                                                                                                 
4                                               1343.7                                                                                                 
..                                                 ...                                                                                                 
424                                               29.2                                                                                                 
425                                               27.2                                                                                                 
426                                               31.8                                                                                                 
427                                               29.2                                                                                                 
428                                               48.1                                                                                                 

     Gross value added (millions of euro), L Real estate activities  
0                                               4110.6               
1                                               4309.0               
2                                               4661.6               
3                                               4864.7               
4                                               4920.7               
..                                                 ...               
424                                              128.8               
425                                              136.4               
426                                              134.4               
427                                              133.0               
428                                              165.8               

[429 rows x 5 columns]

In [29]:
from data_cleaning import split_code_from_name, ffill_col

reminaining_industries_df = ffill_col(remaining_industries_df, "Region")
remaining_industries_df = split_code_from_name(remaining_industries_df, "Region", code_length=2)
remaining_industries_df

Region  Year  \
0       01  2000   
1       01  2001   
2       01  2002   
3       01  2003   
4       01  2004   
..     ...   ...   
424     21  2018   
425     21  2019   
426     21  2020   
427     21  2021   
428     21  2022   

     Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                              15598.9               
1                                              16651.9               
2                                              15138.7               
3                                              15059.6               
4                                              15142.6               
..                                                 ...               
424                                               94.4               
425                                              111.7               
426                                              109.5               
427                                              132.4               
428                                              135.7               

     Gross value added (millions of euro), D, E Electricity, gas, steam and air conditioning and water supply; sewerage and waste management (35-39)  \
0                                                964.9                                                                                                 
1                                               1049.8                                                                                                 
2                                               1145.8                                                                                                 
3                                               1354.2                                                                                                 
4                                               1343.7                                                                                                 
..                                                 ...                                                                                                 
424                                               29.2                                                                                                 
425                                               27.2                                                                                                 
426                                               31.8                                                                                                 
427                                               29.2                                                                                                 
428                                               48.1                                                                                                 

     Gross value added (millions of euro), L Real estate activities  
0                                               4110.6               
1                                               4309.0               
2                                               4661.6               
3                                               4864.7               
4                                               4920.7               
..                                                 ...               
424                                              128.8               
425                                              136.4               
426                                              134.4               
427                                              133.0               
428                                              165.8               

[429 rows x 5 columns]

In [36]:
from data_cleaning import pad_code
regional_df["Region"] = pad_code(regional_df, "Region", code_length=2)
regional_df

Region  Year  GDP per capita (euro)  Imports (euro)  Exports (euro)  \
0       01  2000                36270.1             NaN             NaN   
1       01  2001                38454.8             NaN             NaN   
2       01  2002                38552.7             NaN             NaN   
3       01  2003                38643.2             NaN             NaN   
4       01  2004                40312.2             NaN             NaN   
..     ...   ...                    ...             ...             ...   
470     21  2020                39532.8    5.976800e+10    5.744000e+10   
471     21  2021                44250.6    7.293600e+10    6.890800e+10   
472     21  2022                48912.8    9.246900e+10    8.188500e+10   
473     21  2023                    NaN    7.684900e+10    7.636200e+10   
474     21  2024                    NaN    7.455700e+10    7.210400e+10   

     Gross value added (millions of euro), A Agriculture, forestry and fishing  \
0                                                255.5                           
1                                                235.4                           
2                                                246.1                           
3                                                235.6                           
4                                                233.9                           
..                                                 ...                           
470                                               31.3                           
471                                               29.3                           
472                                               21.7                           
473                                               26.4                           
474                                                NaN                           

     Gross value added (millions of euro), B Mining and quarrying  \
0                                                 40.8              
1                                                 43.4              
2                                                 39.1              
3                                                 34.6              
4                                                 42.8              
..                                                 ...              
470                                                1.5              
471                                                1.7              
472                                                1.7              
473                                                NaN              
474                                                NaN              

     Gross value added (millions of euro), F Construction  \
0                                               2501.6      
1                                               2766.6      
2                                               2449.9      
3                                               2567.0      
4                                               2754.4      
..                                                 ...      
470                                               89.4      
471                                               94.3      
472                                               83.0      
473                                                NaN      
474                                                NaN      

     Gross value added (millions of euro), G Wholesale and retail trade; repair of motor vehicles and motorcycles  \
0                                               5985.4                                                              
1                                               6491.5                                                              
2                                               6530.9                                                              
3                                               6380.4                                  

In [37]:
from data_cleaning import merge_with_final

# Region should be int, Year int
remaining_industries_df["Region"] = remaining_industries_df["Region"].astype(str)
remaining_industries_df["Year"] = remaining_industries_df["Year"].astype(int)
# merge remaining_industries_df with regional_df, save to regional_path
regional_df = pd.merge(
    left=regional_df,
    right=remaining_industries_df,
    how="outer",
    on=["Region", "Year"]
)
regional_df

Region  Year  GDP per capita (euro)  Imports (euro)  Exports (euro)  \
0       01  2000                36270.1             NaN             NaN   
1       01  2001                38454.8             NaN             NaN   
2       01  2002                38552.7             NaN             NaN   
3       01  2003                38643.2             NaN             NaN   
4       01  2004                40312.2             NaN             NaN   
..     ...   ...                    ...             ...             ...   
899    nan  2022                    NaN             NaN             NaN   
900    nan  2022                    NaN             NaN             NaN   
901    nan  2022                    NaN             NaN             NaN   
902    nan  2022                    NaN             NaN             NaN   
903    nan  2022                    NaN             NaN             NaN   

     Gross value added (millions of euro), A Agriculture, forestry and fishing  \
0                                                255.5                           
1                                                235.4                           
2                                                246.1                           
3                                                235.6                           
4                                                233.9                           
..                                                 ...                           
899                                                NaN                           
900                                                NaN                           
901                                                NaN                           
902                                                NaN                           
903                                                NaN                           

     Gross value added (millions of euro), B Mining and quarrying  \
0                                                 40.8              
1                                                 43.4              
2                                                 39.1              
3                                                 34.6              
4                                                 42.8              
..                                                 ...              
899                                                NaN              
900                                                NaN              
901                                                NaN              
902                                                NaN              
903                                                NaN              

     Gross value added (millions of euro), F Construction  \
0                                               2501.6      
1                                               2766.6      
2                                               2449.9      
3                                               2567.0      
4                                               2754.4      
..                                                 ...      
899                                                NaN      
900                                                NaN      
901                                                NaN      
902                                                NaN      
903                                                NaN      

     Gross value added (millions of euro), G Wholesale and retail trade; repair of motor vehicles and motorcycles  \
0                                               5985.4                                                              
1                                               6491.5                                                              
2                                               6530.9                                                              
3                                               6380.4                                  

In [39]:
# save to csv
regional_df.to_csv(regional_path, index=False)

In [41]:
# merge remaining_industries_df with final_df, save to final_path
remaining_industries_df["Municipality"] = "TOTAL"
final_df = merge_with_final(final_df, remaining_industries_df)
final_df

Region  Year  \
0        01  2000   
1        01  2001   
2        01  2002   
3        01  2003   
4        01  2003   
...     ...   ...   
8017    nan  2022   
8018    nan  2022   
8019    nan  2022   
8020    nan  2022   
8021    nan  2022   

      Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                                   NaN               
1                                                   NaN               
2                                                   NaN               
3                                                   NaN               
4                                                   NaN               
...                                                 ...               
8017                                              852.3               
8018                                             4966.4               
8019                                              435.8               
8020                                             2334.6               
8021                                              135.7               

      Gross value added (millions of euro), D, E Electricity, gas, steam and air conditioning and water supply; sewerage and waste management (35-39)  \
0                                                   NaN                                                                                                 
1                                                   NaN                                                                                                 
2                                                   NaN                                                                                                 
3                                                   NaN                                                                                                 
4                                                   NaN                                                                                                 
...                                                 ...                                                                                                 
8017                                              112.1                                                                                                 
8018                                              645.7                                                                                                 
8019                                              216.5                                                                                                 
8020                                              402.8                                                                                                 
8021                                               48.1                                                                                                 

      Gross value added (millions of euro), L Real estate activities  \
0                                                   NaN                
1                                                   NaN                
2                                                   NaN                
3                                                   NaN                
4                                                   NaN                
...                                                 ...                
8017                                              307.5                
8018                                             1980.4                
8019                                              331.7                
8020                                              862.5                
8021                                              165.8                

     Municipality  GDP per capita (euro at current prices)  Imports (euro)  \
0           TOTAL                                  36270.1             NaN   
1           TOTAL                        

In [43]:
# sort final_df correctly so within each region, Years are in order and municipalities are sorted by code (ending with "TOTAL")
final_df = final_df.sort_values(["Region", "Year", "Municipality"])
final_df

Region  Year  \
0        01  2000   
1        01  2001   
2        01  2002   
3        01  2003   
4        01  2003   
...     ...   ...   
8017    nan  2022   
8018    nan  2022   
8019    nan  2022   
8020    nan  2022   
8021    nan  2022   

      Gross value added (millions of euro), C Manufacturing (10-33)  \
0                                                   NaN               
1                                                   NaN               
2                                                   NaN               
3                                                   NaN               
4                                                   NaN               
...                                                 ...               
8017                                              852.3               
8018                                             4966.4               
8019                                              435.8               
8020                                             2334.6               
8021                                              135.7               

      Gross value added (millions of euro), D, E Electricity, gas, steam and air conditioning and water supply; sewerage and waste management (35-39)  \
0                                                   NaN                                                                                                 
1                                                   NaN                                                                                                 
2                                                   NaN                                                                                                 
3                                                   NaN                                                                                                 
4                                                   NaN                                                                                                 
...                                                 ...                                                                                                 
8017                                              112.1                                                                                                 
8018                                              645.7                                                                                                 
8019                                              216.5                                                                                                 
8020                                              402.8                                                                                                 
8021                                               48.1                                                                                                 

      Gross value added (millions of euro), L Real estate activities  \
0                                                   NaN                
1                                                   NaN                
2                                                   NaN                
3                                                   NaN                
4                                                   NaN                
...                                                 ...                
8017                                              307.5                
8018                                             1980.4                
8019                                              331.7                
8020                                              862.5                
8021                                              165.8                

     Municipality  GDP per capita (euro at current prices)  Imports (euro)  \
0           TOTAL                                  36270.1             NaN   
1           TOTAL                        

In [44]:
final_df.to_csv(final_path, index=False)